### ISSUE TITLE
能否在category-ads中移除alibaba的四个域名“gtms0x.alicdn.com”

### ISSUE THREAD

**Issue by techxiu** [v2ray/domain-list-community#106]
能否移除以下四个域名，屏蔽后导致下面的阿里云付款界面的图片打不开
https://gtms01.alicdn.com/tps/i4/T17IKqFbXeXXbb9.QQ-442-311.png
gtms01.alicdn.com @ads
gtms02.alicdn.com @ads
gtms03.alicdn.com @ads
gtms04.alicdn.com @ads
![截屏2019-11-09下午4.05.28.png](https://i.loli.net/2019/11/09/658eTbziRkDN1BE.png)

**Comment by iochen** [comment]
Because there are also some banner ads under this URL, we cannot do that. Besides, some other URLs have the same problem.

You can remove it from your own rules and use some extensions to block remaining ads.

**Comment by techxiu** [comment]
Okay, I know👌
