### ISSUE TITLE
add a new attribute for tracker domains

### ISSUE THREAD

**Issue by rhjdvsgsgks** [v2ray/domain-list-community#196]
such as almost all umeng domains

**Comment by Loyalsoldier** [comment]
There are no tracker domains in the repo.

**Comment by rhjdvsgsgks** [comment]
is there any plans to add them?

**Comment by iochen** [comment]
> is there any plans to add them?

No at present.

But you can make it yourself, using the data here https://github.com/EFForg/privacybadger/tree/master/src/data .

**Comment by rhjdvsgsgks** [comment]
thanks
