### ISSUE TITLE
I'm curious about the reason why the dlc.dat file reduces about 500KB in size suddenly.

### ISSUE THREAD

**Issue by Loyalsoldier** [v2ray/domain-list-community#198]
No build errors. No problem with the speedtest generation script.

![image](https://user-images.githubusercontent.com/10487845/73588601-08530400-4506-11ea-8afc-2d5651bb4b8c.png)

**Comment by iochen** [comment]
I viewed that, some data get lost.
I'm looking into it.

**Comment by iochen** [comment]
![image](https://user-images.githubusercontent.com/28243989/73589794-0abd5a00-4516-11ea-9078-a21542de38b7.png)

![image](https://user-images.githubusercontent.com/28243989/73589775-d9dd2500-4515-11ea-8ef7-c8e886e9cea3.png)

**Comment by Loyalsoldier** [comment]
curl only downloads about 100 lines of speedtest domains. That's strange.

![image](https://user-images.githubusercontent.com/10487845/73589854-93d49100-4516-11ea-9c02-cf16668808de.png)

**Comment by iochen** [comment]
Nothing writes into it, it's weird.
![image](https://user-images.githubusercontent.com/28243989/73589999-2c1f4580-4518-11ea-99b4-7150b1b0fe31.png)

**Comment by iochen** [comment]
I found it out.

https://c.speedtest.net/speedtest-servers-static.php didn't return a correct xml file, a html page instead.

![image](https://user-images.githubusercontent.com/28243989/73590077-25450280-4519-11ea-9d5d-84a3483fd7b3.png)
![image](https://user-images.githubusercontent.com/28243989/73590085-2e35d400-4519-11ea-99df-b4b02407d052.png)

**Comment by Loyalsoldier** [comment]
I try wget. It responds 503 Status code. Then I try curl with Chrome User-Agent. It downloads the same content as without Chrome user-agent.

I think speedtest has banned Microsoft IPs.

**Comment by iochen** [comment]
We have to use a former form, update it at a certain time instead of using GitHub Actions may be the only choice now.

**Comment by Loyalsoldier** [comment]
Agree.

**Comment by kslr** [comment]
Azure Cloud Ubuntu

curl 'https://c.speedtest.net/speedtest-servers-static.php' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: zh-CN,en;q=0.8,zh-TW;q=0.5,ja;q=0.3' --compressed -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'Cache-Control: max-age=0' -H 'TE: Trailers'

success

**Comment by iochen** [comment]
I tested few more times.
If I enable gzip (add Header `Accept-Encoding: gzip`), it will return correct content.
If I don't, it won't.
