### ISSUE TITLE
请问支持youtube的广告过滤吗？

### ISSUE THREAD

**Issue by fanchangyong** [v2ray/domain-list-community#200]
我试了一下国内的，好像iqiyi是可以过滤广告的，但是youtube还是有广告。
请问是数据不支持youtube的广告过滤吗?

**Comment by kslr** [comment]
是的，没有人提交这一项。

**Comment by Loyalsoldier** [comment]
YouTube 的广告不能通过屏蔽某个域名来实现，否则视频会无法正常播放，还是通过浏览器广告屏蔽插件来得方便得多。况且，V2Ray 不支持 HTTPS 解密拦截广告请求。

**Comment by fanchangyong** [comment]
电脑上的可以通过浏览器插件过滤，手机上的YouTube广告有办法过滤吗

**Comment by iochen** [comment]
Watch through browser may be the only choice.
You can try https://adguard.com/en/article/how-to-block-ads-on-youtube.html#6 or some other apps.

**Comment by Loyalsoldier** [comment]
@fanchangyong 
请下载安装支持 HTTPS 解密功能的客户端，并配合 YouTube 广告规则使用。

**Comment by fanchangyong** [comment]
好的，谢谢

**Comment by piaoliuhe** [comment]
最终没有搞明白，V2rayN是如何屏蔽youtube广告的，每看一会儿就弹出广告，必须要手动点跳过，十分影响观看效率，我看到youtube上面有博主在shadowrocket上导出代码屏蔽广告，v2rayN有相关的设置吗，期待改善。

**Comment by piaoliuhe** [comment]
> [@fanchangyong](https://github.com/fanchangyong) 请下载安装支持 HTTPS 解密功能的客户端，并配合 YouTube 广告规则使用。

没明白，什么意思？
