### ISSUE TITLE
Error saving asset

### ISSUE THREAD

**Issue by iochen** [v2ray/domain-list-community#231]
![image](https://user-images.githubusercontent.com/28243989/75354103-685f7f00-58e7-11ea-88ba-403e34c15a2e.png)
![image](https://user-images.githubusercontent.com/28243989/75354158-7c0ae580-58e7-11ea-8bf7-71264cd6a02f.png)

**Comment by Loyalsoldier** [comment]
My fork is okay: https://github.com/Loyalsoldier/domain-list-community/releases

This error appears from time to time in my [v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat) project. I think it is the problem of the github action `Ricky-Hao/action-release@master`

**Comment by iochen** [comment]
Maybe we should retrig it.

**Comment by Loyalsoldier** [comment]
I will try another GitHub action to release assets.
