### ISSUE TITLE
建议增加国外常用CDN的IP段

### ISSUE THREAD

**Issue by zenyanbo** [v2ray/domain-list-community#255]
为了帮助默认直连的配置(gfwlist-black)加速使用海外CDN的网站，以下我收集的CDNIP段，希望大家多多补充。
CloudFlare：
          "173.245.48.0\/20",
          "103.21.244.0\/22",
          "103.22.200.0\/22",
          "103.31.4.0\/22",
          "141.101.64.0\/18",
          "108.162.192.0\/18",
          "190.93.240.0\/20",
          "188.114.96.0\/20",
          "197.234.240.0\/22",
          "198.41.128.0\/17",
          "162.158.0.0\/15",
          "104.16.0.0\/12",
          "172.64.0.0\/13",
          "131.0.72.0\/22",
          "2400:cb00::\/32",
          "2606:4700::\/32",
          "2803:f800::\/32",
          "2405:b500::\/32",
          "2405:8100::\/32",
          "2a06:98c0::\/29",
          "2c0f:f248::\/32"

AWS：
          "144.220.0.0\/16",
          "52.124.128.0\/17",
          "54.230.0.0\/16",
          "54.239.128.0\/18",
          "52.82.128.0\/19",
          "99.84.0.0\/16",
          "204.246.172.0\/24",
          "54.239.192.0\/19",
          "70.132.0.0\/18",
          "13.32.0.0\/15",
          "205.251.208.0\/20",
          "13.224.0.0\/14",
          "13.35.0.0\/16",
          "204.246.164.0\/22",
          "204.246.168.0\/22",
          "71.152.0.0\/17",
          "216.137.32.0\/19",
          "205.251.249.0\/24",
          "99.86.0.0\/16",
          "52.46.0.0\/18",
          "52.84.0.0\/15",
          "204.246.173.0\/24",
          "130.176.0.0\/16",
          "205.251.200.0\/21",
          "204.246.174.0\/23",
          "64.252.128.0\/18",
          "205.251.254.0\/24",
          "143.204.0.0\/16",
          "205.251.252.0\/23",
          "204.246.176.0\/20",
          "13.249.0.0\/16",
          "54.240.128.0\/18",
          "205.251.250.0\/23",
          "52.222.128.0\/17",
          "54.182.0.0\/16",
          "54.192.0.0\/16",

**Comment by Loyalsoldier** [comment]
这个项目只负责处理域名。

**Comment by zenyanbo** [comment]
噢，对。。。
