### ISSUE TITLE
在用投影仪投屏youku视频时卡住

### ISSUE THREAD

**Issue by dawncold** [v2ray/domain-list-community#348]
投屏youku视频时投影仪卡住，我看日志发现block了这个域名：vali.cp31.ott.cibntv.net

把这个域名加入到direct中后投屏正常，请大家测试一下？

**Comment by EpLiar** [comment]
直接访问 403

**Comment by iochen** [comment]
https://github.com/zhangn1985/ykdl/issues/321#issue-356650818

此域的确是一个视频源
