### ISSUE TITLE
sina-ads是否太严格了

### ISSUE THREAD

**Issue by bash99** [v2ray/domain-list-community#371]
cre.mix.sina.com.cn 是相关新闻feed流，虽然类头条模式的无限下拉令人讨厌，算成广告又感觉有点严格。

**Comment by kslr** [comment]
你需要提供一些说明

**Comment by bash99** [comment]
> 你需要提供一些说明

访问如下地址可以看见返回内容是新闻标题和链接，封掉此域名后，新浪新闻下的相关新闻打不开。

curl 'https://cre.mix.sina.com.cn/api/v3/get?callback=jQuery111105268452408846549_1587629061935&cateid=sina_all&cre=tianyi&mod=pcpager_inter&merge=3&statics=1&this_page=1&length=40&up=1&down=0&pageurl=https%3A%2F%2Fnews.sina.com.cn%2Fw%2F2020-04-23%2Fdoc-iirczymi7915568.shtml&imp_type=2&action=1&fields=media%2Cauthor%2Clabels_show%2Ccommentid%2Ccomment_count%2Ctitle%2Cltitle%2Curl%2Cinfo%2Cthumbs%2Cthumb%2Cctime%2Creason%2Ccategory%2Cvideo_id%2ChotTag%2Cimg_count%2Cgif%2Clive_stime%2Clive_etime%2Cmedia_id%2Csummary%2CorgUrl%2Cshow%2Cintro%2Cdocid%2Cplaytimes%2Cvideo_height%2Cvideo_width%2Ctime_length%2Cuser_icon%2Cuid%2Curl_https&tm=1587629070&offset=0&ad=%7B%22rotate_count%22%3A100%2C%22platform%22%3A%22pc%22%2C%22channel%22%3A%22tianyi_pcpager_inter%22%2C%22page_url%22%3A%22https%3A%2F%2Fnews.sina.com.cn%2Fw%2F2020-04-23%2Fdoc-iirczymi7915568.shtml%22%2C%22timestamp%22%3A1587629070039%7D&_=1587629061938' -H 'Connection: keep-alive' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/80.0.3987.163 Chrome/80.0.3987.163 Safari/537.36' -H 'Sec-Fetch-Dest: script' -H 'Accept: */*' -H 'Sec-Fetch-Site: same-site' -H 'Sec-Fetch-Mode: no-cors' -H 'Referer: https://news.sina.com.cn/w/2020-04-23/doc-iirczymi7915568.shtml' -H 'Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7' --compressed

**Comment by Loyalsoldier** [comment]
查看过 Easylist 和 Easylist China，确实没有这个域名。
