### ISSUE TITLE
能否添加命令行选项并且不需依赖 gopath?

### ISSUE THREAD

**Issue by ayasechan** [v2ray/domain-list-community#401]
如题

**Comment by Loyalsoldier** [comment]
由于本项目依赖别的包，没有 `$GOPATH` 会导致依赖包无法安装。

PR #402 添加了 `--datapath` 选项，用于指定自定义 data 文件夹。使用方法：

1. 如果不显式设置 `$GOPATH` 导致错误提示找不到依赖包的话，请先显式设置 `$GOPATH`
2. 安装依赖包：
	`go get -v -u github.com/golang/protobuf/proto`
	`go get -v -u --insecure v2ray.com/core/app/router`
3. git clone 本项目
4. 在项目目录中运行：`go run main.go --datapath=path/to/your/custom/data/folder`。例如：`go run main.go --datapath=./data`
