### ISSUE TITLE
如何配置代理转发

### ISSUE THREAD

**Issue by TinyTinyHuang** [v2ray/domain-list-community#422]
v2ray教程里面是有代理转发的配置,也就是数据可以先到A服务器,然后传到B服务器,然后再传出去.
这里面可以配置代理转发吗?

**Comment by TinyTinyHuang** [comment]
为什么关闭问题？

**Comment by Loyalsoldier** [comment]
V2Ray 使用问题请到 https://github.com/v2ray/discussion/issues 开 issue
