### ISSUE TITLE
关于域名组织归属书写方式的意见收集

### ISSUE THREAD

**Issue by EpLiar** [v2ray/domain-list-community#472]
在此仓库的域名管理形式中，如果一家公司有子公司的情况会有两种写法，如 `data/alibaba`：

https://github.com/v2ray/domain-list-community/blob/d882f0a1d8cbd16375516e056eaf79dfd07416c6/data/alibaba#L122-L136

https://github.com/v2ray/domain-list-community/blob/d882f0a1d8cbd16375516e056eaf79dfd07416c6/data/alibaba#L158

前者为子公司的所有域名直接写到 `data/alibaba` 中，后者为单独一个文件再进行 `include`。

在我发现 `data/eleme` 为阿里的子公司的时候，拿不定使用哪种引用形式，因此开了此 issue 供大家讨论，希望能得出一个比较合适的方式。

**Comment by Loyalsoldier** [comment]
我的想法是，本来已经有一个独立的文件的话，就不要合并进去，而是通过 `include` 的方式来加入到别的独立文件中，例如 `teambition` 本来已经存在。

因为有可能本来某些海外用户要对 `teambition` 使用代理来访问，在 V2Ray 配置文件中单独添加了 `geosite:teambiton` 这一项。而更新 dat 文件后，如果这个项目消失了，V2Ray 会报错，无法启动，用户会一脸懵。

另外，例如 `alibabacloud.com` （海外版的阿里云）这种明显是海外用户才会访问的域名，我觉得不适合混入到 `alibaba` 这个文件里面，而是通过独立文件进行 `include`。方便海外用户在配置文件中单独为 `geosite:alibabacloud` 指定路由规则。

别的没什么意见。另外，我一般不会主动添加大陆的域名。对于大陆域名，你觉得怎么 okay 怎么来。

**Comment by EpLiar** [comment]
> 我的想法是，本来已经有一个独立的文件的话，就不要合并进去，而是通过 `include` 的方式来加入到别的独立文件中，例如 `teambition` 本来已经存在。
> 
> 因为有可能本来某些海外用户要对 `teambition` 使用代理来访问，在 V2Ray 配置文件中单独添加了 `geosite:teambiton` 这一项。而更新 dat 文件后，如果这个项目消失了，V2Ray 会报错，无法启动，用户会一脸懵。
> 
> 另外，例如 `alibabacloud.com` （海外版的阿里云）这种明显是海外用户才会访问的域名，我觉得不适合混入到 `alibaba` 这个文件里面，而是通过独立文件进行 `include`。方便海外用户在配置文件中单独为 `geosite:alibabacloud` 指定路由规则。
> 
> 别的没什么意见。另外，我一般不会主动添加大陆的域名。对于大陆域名，你觉得怎么 okay 怎么来。

我也觉得单独文件好一些
