### ISSUE TITLE
问卷星部分网站未能直连

### ISSUE THREAD

**Issue by DuckSoft** [v2ray/domain-list-community#478]
![图片](https://user-images.githubusercontent.com/7822648/83971820-d9afc480-a90f-11ea-8156-d8aba171e556.png)
如图，image.wjx.com 仍然代理

**Comment by EpLiar** [comment]
我在 https://site.ip138.com/image.wjx.com/ 解析 image.wjx.com 时发现有一个结果是到中国香港，不知道和这个有没有关系

![image](https://user-images.githubusercontent.com/23559565/84454658-c729e800-ac8d-11ea-92b5-1020ac732bdd.png)

比较合适还是创建一个 `data/wjx` 吧

**Comment by EpLiar** [comment]
> 我在 https://site.ip138.com/image.wjx.com/ 解析 image.wjx.com 时发现有一个结果是到中国香港，不知道和这个有没有关系
> 
> ![image](https://user-images.githubusercontent.com/23559565/84454658-c729e800-ac8d-11ea-92b5-1020ac732bdd.png)
> 
> 比较合适还是创建一个 `data/wjx` 吧

已创建 `data/wjx` https://github.com/v2ray/domain-list-community/pull/496

**Comment by DuckSoft** [comment]
worked for me. closing!
thank you!
