### ISSUE TITLE
Add smart tv app domain

### ISSUE THREAD

**Issue by realEthanZou** [v2ray/domain-list-community#503]
Not sure where to put it so I'll just leave it here.
ottcn.com  # 聚好看
aisee.tv  # 云视听小电视

**Comment by kslr** [comment]
可以用厂商分开，然后包含到geo cn中

**Comment by realEthanZou** [comment]
> 可以用厂商分开，然后包含到geo cn中

感觉域名都像是归属牌照合作方之类的，不确定是否负责多个 app，感觉就划在 腾讯 / 哔哩哔哩 下也不太合适。

**Comment by kslr** [comment]
现在的话单独归类到 category-smarttv-cn 呢
