### ISSUE TITLE
[Feature Discussion] support priority settings

### ISSUE THREAD

**Issue by iochen** [v2ray/domain-list-community#552]
Default priority is 99, and set it when is needed.
Priority of 1 is the highest, the higher the number the lower the priority.
Every priority begins with `!`, followed by the priority

example:
```
zoom.com
zoom.com.cn !100
zoom.us
```
and in this way, `zoom.com.cn` would be treated as `tld-cn`.

Similarly, #487 can be solved.

**Comment by Loyalsoldier** [comment]
Is this a proposal, or it has already been implemented in V2Ray?

**Comment by iochen** [comment]
> Is this a proposal, or it has already been implemented in V2Ray?

A proposal.

**Comment by Loyalsoldier** [comment]
IMO, two ways to solve the problem in #487 
1. we should divide `apple` to `apple` and `apple-cn`, the same to `google` and `microsoft`, etc
2. we should NOT include domains that end with `.cn` or those who use CDN in China mainland in `geolocation-!cn` category, and leave them to DNS resolver(or user) to decide which outbound to use (because some users use proxy outbound as fallback while others use direct outbound)

**Comment by EpLiar** [comment]
> 1. we should divide `apple` to `apple` and `apple-cn`, the same to `google` and `microsoft`, etc

I'm inclined to agree with that solution. But it may require frequent maintenance.

> 2. we should NOT include domains that end with `.cn` or those who use CDN in China mainland in `geolocation-!cn` category, and leave them to DNS resolver(or user) to decide which outbound to be used (because some users use proxy outbound as fallback while others use direct outbound)

If so, a user who wants to block an organization's domain cannot block it in full. (Even in a few cases)

Both options are possible and it seems we need a vote or discussion to decide the final solution.

@Loyalsoldier

**Comment by Loyalsoldier** [comment]
认真思考了这个问题后，我觉得增加优先级功能并不能彻底解决 CDN 域名到底是走代理还是直连的问题，因为本身设置多大的优先级到列表中，是由本项目贡献者决定的，而这个问题的最终解决方案应该是交给用户（DNS 配置、路由配置），让用户在配置文件中设置。

例如，对于 apple 这种不是中国大陆的公司，本项目应该默认让其走代理。而其在中国大陆有 CDN 域名的话，可以独立出类别 `apple-cdn` 或者 `apple-cn`，但是不加入到 `geolocation-cn` 类别中，最终由用户决定是否通过 `geosite:apple-cdn` 的方式加入到配置文件中（不主动设置，则默认走代理）。

而对于类似阿里巴巴这种在中国大陆的公司，本项目应该默认让其直连。如果其有海外业务，则将独立列表例如 `alibabacloud`提交到本项目中后，加入到 `geolocation-!cn` 类别中。

**Comment by Robot-DaneelOlivaw** [comment]
Users can always throw the whole `geosite:apple` to DNS and only taking direct outbound when IP located in mainland China is returned (or Hong Kong, Macau, Taiwan, Japan, Singapore). Same can be applied to `geosite:microsoft`. All we need to do is to cover as many Apple's domains as possible.

According to the document, V2Ray tries routing rules from top down one by one. As long as you put `geosite:cn` on top, it doesn't really matter whether `.cn` is included into `apple` or not.

But sometimes, even when some domains have access points in China, they are slow. Users may want to use proxy for those services without affecting the whole group. So it might be useful to sort out subdomains in new lists or label them with `attr`.
