### ISSUE TITLE
Category-ads-all 里的 atianqi.com 全域名屏蔽导致腾讯TV app 崩溃

### ISSUE THREAD

**Issue by jitdor** [v2ray/domain-list-community#664]
目前如果启用 geosite:category-ads-all 广告域名屏蔽，里面的 xiaomitv-ads 规则会屏蔽了整个 atianqi.com 域名。但是极光TV（腾讯视频TV电视版）必需读取特定 atianqi.com 子域名（例如 tv.aiseet.atianqi.com 和 *.play.aiseet.atianqi.com）才能使用，也并非整个 atianqi.com 域名都是广告。

**Comment by Loyalsoldier** [comment]
Fixed in https://github.com/v2fly/domain-list-community/pull/233

Please download the latest `dlc.dat` as `geosite.dat` from https://github.com/v2fly/domain-list-community/releases
