### ISSUE TITLE
Category-ads-all 屏蔽cbu01.alicdn.com域名，导致1688图片无法显示

### ISSUE THREAD

**Issue by wongzeon** [v2ray/domain-list-community#669]
路由设置block规则为category-ads-all，会屏蔽cbu01.alicdn.com，导致访问1688时商品图片无法被加载

**Comment by Loyalsoldier** [comment]
Fixed by https://github.com/v2fly/domain-list-community/pull/519

Please use https://github.com/v2fly/domain-list-community instead.
