### ISSUE TITLE
Note that sometimes it might cause issues that can be hard to debug

### ISSUE THREAD

**Issue by Xyncgas** [v2ray/domain-list-community#67]
Because the rules are in the domain-list, thus it's hard to debug
when users choose to use these setting, they route the traffics to their servers, now some companies and websites they know these servers, and they blocked them in advance to prevent DDOS, so if some dumb user let's just say 30% of our community here have used the domain list, they will begin to notice that they are not able to go to some websites and dont know why, because the rules are in the domain list files it becomes less informative when you encounter the issues.
BUT WELL NOW YOU KNOW

**Comment by kslr** [comment]
Not used by default
