### ISSUE TITLE
Category-ads-all 屏蔽了 btrace.qq.com，会导致QQ的快捷登录无法识别到本地客户端

### ISSUE THREAD

**Issue by wongzeon** [v2ray/domain-list-community#670]
日志：127.0.0.1:10270 accepted //btrace.qq.com:443 [block]
btrace.qq.com 被屏蔽后，本地客户端的登录状态无法被识别，无法使用QQ快捷登录。

**Comment by Loyalsoldier** [comment]
建议把 `btrace.qq.com` 显式设置为直连后测试。印象中 QQ 无法快捷登录好像不是某个域名的问题。如果我记错了，欢迎提醒。

**Comment by wongzeon** [comment]
嗯，测试发现没问题了。这个网址只是偶然出现，出现的时候页面就加载不出客户端登录的账号。

**Comment by kslr** [comment]
需要设置 private 直连
